### PR TITLE
Add `replace_values_inplace_using_mask()`

### PR DESCRIPTION
**Pull request by trivoldus28**
Useful for correcting split/merge errors in the segmentation
file using fragments as mask.

### CODE REVIEW

**Comment by funkey** [comment]
I am not sure if I understand what this new function does. From the name and docstring, I think it is supposed to limit the relabelling to a binary mask, is that right? If so:
1. I don't see where this actually happens. In particular, I would expect the code to check at some point that the mask is non-zero and only change values in `out` at these locations.
2. Couldn't this be done with the existing method: `a[mask] = replace_values(a[mask], old_values, new_values)`?

But maybe I am reading this wrong and you want to relabel values `old_values` with `new_values` in an array `a`, but instead of writing to `a` you want to write to `b`? In this case:
1. It would be enough to have a third argument to `replace_values_inplace` (the `out` array) and have it be the same as `array` by default. This would avoid having a new function that is almost exactly identical to the existing `replace_values_inplace`.
2. Similarly, `replace_values` could take an optional `out` argument, which if set to `None` returns a new array, if set to `array` performs in-place replace (deprecating current parameter `inplace`), and if set to another array implements the described behavior.

**Comment by funkey** [comment]
Also, please add unit tests :)

**Comment by trivoldus28** [comment]
It's neither :).

My use case was that given a `fragment_array`, and a map of fragment to be relabeled `fragment_map`, I would like to relabel the `segmentation_array`. The equivalent code in python and numpy would be something like this:
```
for fragment_id in fragment_map:
    new_label = fragment_map[fragment_id]
    np.place(segmentation_array, fragment_array == fragment_id, [new_label])
```

**Comment by funkey** [comment]
Is it really neither? It seems you can do what you describe with my second proposal (optional `out` argument), like this:
```
old_values = np.array(fragment_map.keys())
new_values = np.array(fragment_map.values())
replace_values(fragment_array, old_values, new_values, out=segmentation_array)
```

**Comment by trivoldus28** [comment]
Got it, I think your suggestion makes sense now.

**Comment by trivoldus28** [comment]
@funkey I merged the "mask" functionality to `replace_values` now, wrote tests, and add a few other niceties as documented in the commit message.

Note: Originally I took out the `inplace` param, but decided to keep in for compatibility purposes.

**Comment by funkey** [comment]
Thanks a lot!

**Pull request merged**
